---
  - name: Congif Web VM with Docker
    hosts: webservers
    become: true
    tasks:

    - name: Uninstall apache2
      apt:
        name: apache2
        state: absent

    - name: Install Docker.io
      apt:
        name: docker.io
        state: present

    - name: Install PIP
      apt:
        name: python-pip
        state: present

    - name: Install Docker python module
      pip:
        name: docker
        state: present

    - name: Download and launche a docker web container
      docker_container:
        name: dvwa
        image: cyberxsecurity/dvwa
        state: started
        published_ports: 80:80